name: Compile and deploy static content to Pages
on:
  push:
    branches: ["1.x", "website"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: "yarn"
      - run: yarn
      - run: node .pages/make.js
      - run: find .pages ! -name 'index.html' -type f -exec rm -f {} +
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: '.pages/static'
      - id: deployment
        uses: actions/deploy-pages@v4
