name: Test
on:
  pull_request:
    paths-ignore:
      - "dist/**"
      - "*.md"
  push:
    branches:
      - "[0-9]+.x"
      - "[0-9]+.x-[a-zA-Z]+"
      - "main"
    paths-ignore:
      - "dist/**"
      - "*.md"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  test:
    name: ${{ matrix.os }}, PHP ${{ matrix.php }}, Laravel ${{ matrix.laravel }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        php: [8.1, 8.2, 8.3]
        laravel: [10, 11]
        exclude:
          - php: 8.1
            laravel: 11
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: fileinfo
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: "yarn"
      - run: composer require laravel/framework:"${{ matrix.laravel }}.*" --no-update --no-interaction
      - uses: ramsey/composer-install@v3
      - run: yarn
      - run: yarn test:all
